require 'guerrilla_patch/string.rb'
require 'guerrilla_patch/kernel.rb'
require 'guerrilla_patch/allocate.rb'
require 'guerrilla_patch/aggregate_by_type/aggregator'
require 'guerrilla_patch/text_matcher'
